# Generated by Django 2.1.7 on 2020-05-10 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PoemData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poemId', models.IntegerField()),
                ('poemDynasty', models.CharField(max_length=10)),
                ('poemTagNames', models.CharField(max_length=100)),
                ('poemStar', models.IntegerField()),
            ],
        ),
    ]
